name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.8
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  notus:
    git:
      url: git://github.com/churchnotesapp/zefyr-master.git
      path: packages/notus/
      ref: 03431899ae5edbc290a326d177fd8087da783e75
  quill_delta: ^3.0.0-nullsafety.2
  html: ^0.15.0

dev_dependencies:
  test: ^1.19.5
