name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.8
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus:
    git:
      url: git://github.com/churchnotesapp/zefyr-master.git
      path: packages/notus/
      ref: 2071d5c4ba5a8c9601330ac4365323ca290d6ef7
      #bdcf3b824d7205aa3f6dce5c6d00a55a8495201c
  quill_delta: ^1.0.2
  html: ^0.14.0

dev_dependencies:
  test:
